---
name: On-Chain News
description: On-Chain News brings you the latest in crypto, defi and nfts
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
email: wowthemesnet@gmail.com
mailchimp-list: ''
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-menus
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  sal:
    name: 'Anthony Blaida '
    site: ''
    avatar: "/assets/images/avatar1.jpg"
    bio: Anthony Blaida , the head of publishing at On Chain News
    email: ''
    twitter: https://twitter.com/onchainnews2
  jane:
    name: 'Alana Sotomayer '
    site: https://www.wowthemes.net
    avatar: "/assets/images/avatar2.jpg"
    bio: Blogger, fashionista, love to explore new ideas and write on crypto!
    email: fakemail@gmail.com
    twitter: https://twitter.com/onchainnews2
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: Anthony
    avatar: "/assets/images/avatar1.jpg"
- scope:
    path: _pages
  values:
    layout: page
paginate: "10"
