---
name: On-Chain News
description: On-Chain News brings you the latest in crypto, defi and nfts
logo: assets/images/on-chainnews.png
favicon: assets/images/favicon.ico
email: admin@on-chain.news.com
mailchimp-list: ''
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-menus
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  Publisher:
    name: On Chain News
    site: ''
    avatar: "/assets/images/on-chainnews.png"
    bio: On Chain News
    email: admin@on-chain.news
    twitter: https://twitter.com/onchainnews2
  jane:
    name: ''
    site: ''
    avatar: ''
    bio: ''
    email: ''
    twitter: ''
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: On Chain News
    avatar: "/assets/images/on-chainnews.png"
- scope:
    path: _pages
  values:
    layout: page
paginate: "10"
